# Generated by Django 5.2.7 on 2025-11-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('route_key', models.CharField(choices=[('NORTE', 'NORTE'), ('SUR', 'SUR')], max_length=10)),
                ('days', models.PositiveIntegerField(default=3)),
                ('Q_proc_m3h', models.FloatField(default=6.0)),
                ('TS_in', models.FloatField(default=0.05)),
                ('TS_cake', models.FloatField(default=0.25)),
                ('eta_captura', models.FloatField(default=0.97)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_run_simulation', 'Puede ejecutar simulaciones QPRESS')],
            },
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.scenario')),
            ],
        ),
    ]
