# Generated by Django 5.2.8 on 2025-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_alter_scenario_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="kpis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
