# Generated by Django 5.2.8 on 2025-11-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_scenario_kpis"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="dehydration_cost_per_m3",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="scenario",
            name="energy_cost_per_kwh",
            field=models.FloatField(default=120.0),
        ),
        migrations.AddField(
            model_name="scenario",
            name="transport_cost_per_km",
            field=models.FloatField(default=1300.0),
        ),
        migrations.AddField(
            model_name="scenario",
            name="volume_m3",
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="days",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
